sudo: false

language: php

cache:
    directories:
        - $HOME/.cache/composer
        - $HOME/.composer/cache
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
    allow_failures:
        - php: 7.1
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"

        - php: 7.0
          env: COVERAGE=true PHPUNIT_FLAGS="--coverage-text"
        - php: 7.1

        - php: 7.0
          env: DEPENDENCIES="symfony/lts:^2" STABILITY="dev"
        - php: 7.1
          env: DEPENDENCIES="symfony/lts:^2" STABILITY="dev"

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - ./vendor/bin/simple-phpunit
