sudo: false

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - SYMFONY_VERSION="^2.8.2"
    - SYMFONY_VERSION="^2.8.2" COMPOSER_FLAGS="--prefer-lowest"

matrix:
    fast_finish: true

    allow_failures:
        - php: 7.2
        - php: hhvm
    include:
        - php: 5.3
          dist: precise
          env: SYMFONY_VERSION="^2.8.2" COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.4
          env: SYMFONY_VERSION="^2.8.2"
        - php: 5.5
          env: SYMFONY_VERSION="^2.8.2"

before_install:
    - if [ "$TRAVIS_PHP_VERSION" == "5.3" ]; then phpenv config-add travis.php.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script: vendor/bin/phpunit --colors
